[2023-12-09 19:08:10,493] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:11,385] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:11] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:11,469] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:11] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:11,471] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:11] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:11,479] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:11] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:11,818] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:11] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:08:27,780] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 88, in predict
    id=form.id,
AttributeError: 'ApanhadoSchema' object has no attribute 'id'
[2023-12-09 19:08:27,786] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:08:27] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:09:24,713] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/schemas/apanhado_schema.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:09:24,853] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:09:41,573] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 87, in predict
    apanhado = Apanhado(
TypeError: __init__() got an unexpected keyword argument 'id'
[2023-12-09 19:09:41,578] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:09:41] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:17,858] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:18,019] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:48,457] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/schemas/apanhado_schema.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:48,711] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:50,163] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:50] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:50,250] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:50] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:50,258] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:50] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:50,259] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:50] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:50,516] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:50] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:10:58,547] WARNING predict() L127  Erro ao adicionar apanhado 'None', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py L127 
[2023-12-09 19:10:58,548] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:10:58] "[31m[1mPOST /apanhado HTTP/1.1[0m" 400 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:12,600] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.2.15:5000 (Press CTRL+C to quit) - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:12,602] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:19,436] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:19] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:19,538] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:19] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:19,539] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:19] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:19,542] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:19] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:19,783] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:19] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 19:11:25,791] WARNING predict() L127  Erro ao adicionar apanhado 'None', N√£o foi poss√≠vel salvar novo item :/ - call_trace=/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py L127 
[2023-12-09 19:11:25,791] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 19:11:25] "[31m[1mPOST /apanhado HTTP/1.1[0m" 400 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
